course_name = "习近平新时代中国特色社会主义思想概论"
course_code = "GEIP1017"
notices = """本课程在 22、23 级为考查课，从 24 级开始改为考试课，请注意考核方式的变化。"""

[[lecturers]]
name = "席伟健"

  [[lecturers.reviews]]
  content = """课堂氛围很好，使用 PPT，但是不会照着念，而是分享有关的故事和理论。无课间，想上厕所自己去。
无点名，但是会排座位表，且座位定期轮换。"""
  author = { name = "", link = "", date = "" }

[[textbooks]]
title = "习近平新时代中国特色社会主义思想概论（2023 年版）"
book_author = "本书编写组"
publisher = "高等教育出版社、人民出版社"
edition = ""
type = "textbook"
author = { name = "", link = "", date = "" }

online_resources = []
course = []
exam = []
lab = []
advice = []
schedule = []
related_links = []
misc = []